cirujanos/apps/about/urls.py
from django.conf.urls import url
from .views import AboutView, ContactFormView, DoctorContentView


urlpatterns = [
    url(r'^$', AboutView.as_view(), name="index"),
    # url(r'^contact/$', 'cirujanos.apps.about.views.contact_us', name="contact"),
    url(r'^doctor/(?P<doctor_code>\w+)/$', DoctorContentView.as_view(),
        name="doctor"),
    url(r'^contact/$', ContactFormView.as_view(), name="contact-us"),
]

cirujanos/apps/home/urls.py
from django.conf.urls import url
from cirujanos.apps.home.views import HomeView

urlpatterns = [
    url(r'^$', HomeView.as_view(), name="index"),
]

cirujanos/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView
from . import views
admin.autodiscover()

urlpatterns = [
    # url(r'^$', TemplateView.as_view(template_name='coming-soon.html')),
    url(r'^$', lambda r: HttpResponseRedirect('home/')),
    url(r'^home/', include('cirujanos.apps.home.urls', namespace="home")),
    url(r'^web/', include('cirujanos.apps.web.urls')),
    url(r'^multimedia/', include('cirujanos.apps.media.urls',
                                 namespace="media")),
    url(r'^about/', include('cirujanos.apps.about.urls', namespace="about")),
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt',
                                               content_type='text/plain')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^tests/$', views.tests_view),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

# from django.conf import settings
# if settings.DEBUG:
#    urlpatterns += patterns(
#        '',
#        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
#            {'document_root': '/path'}),
#    )

handler404 = 'cirujanos.views.error_404_view'
handler500 = 'cirujanos.views.error_500_view'

cirujanos/templates/layout/application.html
{% load staticfiles %}
{% load compress %}
<!DOCTYPE html>
<html>
  <head>
    <title>Cirujanos Torácicos</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% compress css %}
      <link rel="stylesheet" href="{% static 'css/vendor/bootstrap.css' %}">
      <link rel="stylesheet" href="{% static 'css/theme/bootstrap-overrides.css' %}">
      <link rel="stylesheet" href="{% static 'css/theme/theme.css' %}">
      <link rel="stylesheet" href="{% static 'css/lib/animate.css' %}" media="screen, projection" />
    {% endcompress %}

    <!--link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css' -->

    {% block css %}{% endblock %}

    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body class="{{ body_class }}">

    {# HTML Header #}
    {% block header %}{% include 'layout/header.html' %}{% endblock %}

    {# HTML Content  #}
    {% block content %}{% endblock %}

    {# HTML Footer #}
    {% include 'layout/footer.html' %}

    {# Javascript #}
    {% compress js %}{% include 'js_libraries.html' %}{% endcompress %}
    {% if active_menu == "home" %}
      <script type="text/javascript" src="{% static 'js/vendor/index-slider.js' %}"></script>
    {% endif %}
    {% block js %}{% endblock %}
  </body>
</html>

cirujanos/templates/layout/footer.html
<footer id="footer">
  <div class="container">
      <div class="row info">
          <div class="span6 residence">
              <ul>
                  <li>Developed by David Sáenz Tagarro</li>
                  <li>
                    <strong>email:&nbsp;&nbsp;&nbsp;</strong>
                    david.saenz.tagarro@gmail.com
                  </li>
                  <li>
                    <strong>twitter:&nbsp;&nbsp;&nbsp;</strong>
                    @dsaenztagarro
                  </li>
              </ul>
          </div>
      </div>
      <div class="row credits">
          <div class="span12">
              <div class="row copyright">
                  <div class="span12">
                      © 2014 Unidad Especializada Cirujanos Torácicos
                  </div>
              </div>
          </div>
      </div>
  </div>
</footer>

cirujanos/templates/layout/header.html
{% load i18n %}

{% if active_menu == "home" %}
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
{% else %}
<div class="navbar navbar-inverse navbar-static-top" role="navigation">
{% endif %}

  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="{% url 'home:index' %}" class="navbar-brand">Unidad Especializada<br><strong>Cirugía Torácica</strong></a>
    </div>
    <div class="navbar-collapse navbar-ex1-collapse collapse" role="navigation" style="height: auto">
    {% if not menus_hidden %}
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'home:index' %}">INICIO</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle"
            data-toggle="dropdown">SOBRE NOSOTROS<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'about:index' %}">Quienes somos</a></li>
            <li><a href="{% url 'about:contact-us' %}">Contactar</a></li>
          </ul>
        </li>
        <li class="dropdown js-pathology-nav">
          <a href="#" class="dropdown-toggle menu" data-toggle="dropdown">{% trans "pathologies" %}<b class="caret"></b></a>
          <ul class="dropdown-menu">
            {% for pathology in pathology_list %}
            <li>
              <a href="{{ pathology.get_absolute_url }}">{{ pathology.name }}</a>
            </li>
            {% endfor %}
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle menu" data-toggle="dropdown">{% trans "procedures" %}<b class="caret"></b></a>
          <ul class="dropdown-menu">
            {% for procedure in procedure_list %}
            <li>
              <a href="{{ procedure.get_absolute_url }}">{{ procedure.name }}</a>
            </li>
            {% endfor %}
          </ul>
        </li>
        <li><a class="menu" href="{% url 'media:index' %}">{% trans "media" %}</a></li>
      </ul>
    {% endif %}
    </div>
  </div>
</div>